services:
  - type: web
    name: smritisaathi-ner
    repo: https://github.com/Devkishan-kumar-singh/smritisaathi-ner
    branch: main
    autoDeployTrigger: commit
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
